"""add time_blocks table

Revision ID: 0372131ab475
Revises: eabf84cc9eda
Create Date: 2025-12-05 09:03:15.128276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0372131ab475'
down_revision: Union[str, Sequence[str], None] = 'eabf84cc9eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('block_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['business_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_blocks_block_datetime'), 'time_blocks', ['block_datetime'], unique=False)
    op.create_index(op.f('ix_time_blocks_business_id'), 'time_blocks', ['business_id'], unique=False)
    op.create_index(op.f('ix_time_blocks_id'), 'time_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_time_blocks_staff_id'), 'time_blocks', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_blocks_staff_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_business_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_block_datetime'), table_name='time_blocks')
    op.drop_table('time_blocks')
    # ### end Alembic commands ###
