"""add payment configuration and device tables

Revision ID: 28aeae4329cd
Revises: 0372131ab475
Create Date: 2025-12-05 11:50:45.785995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28aeae4329cd'
down_revision: Union[str, Sequence[str], None] = '0372131ab475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('SQUARE', 'CLOVER', name='payment_provider'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_configurations_business_id'), 'payment_configurations', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_configurations_id'), 'payment_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_payment_configurations_provider'), 'payment_configurations', ['provider'], unique=False)
    op.create_table('payment_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pairing_code', sa.String(length=50), nullable=True),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['configuration_id'], ['payment_configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_devices_business_id'), 'payment_devices', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_devices_configuration_id'), 'payment_devices', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_payment_devices_device_id'), 'payment_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_payment_devices_id'), 'payment_devices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_devices_id'), table_name='payment_devices')
    op.drop_index(op.f('ix_payment_devices_device_id'), table_name='payment_devices')
    op.drop_index(op.f('ix_payment_devices_configuration_id'), table_name='payment_devices')
    op.drop_index(op.f('ix_payment_devices_business_id'), table_name='payment_devices')
    op.drop_table('payment_devices')
    op.drop_index(op.f('ix_payment_configurations_provider'), table_name='payment_configurations')
    op.drop_index(op.f('ix_payment_configurations_id'), table_name='payment_configurations')
    op.drop_index(op.f('ix_payment_configurations_business_id'), table_name='payment_configurations')
    op.drop_table('payment_configurations')
    # ### end Alembic commands ###
