"""Add service models and animal type lookup tables

Revision ID: 35d0c7ca3e3b
Revises: 7f3e2d3f5c6b
Create Date: 2025-12-03 12:55:44.827454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35d0c7ca3e3b'
down_revision: Union[str, Sequence[str], None] = '1a4dbf2c9b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('signing_option', sa.Enum('ONCE', 'EVERY', 'MANUAL', name='signingoption'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_id'), 'agreements', ['id'], unique=False)
    op.create_table('animal_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_types_id'), 'animal_types', ['id'], unique=False)
    op.create_index(op.f('ix_animal_types_name'), 'animal_types', ['name'], unique=True)
    op.create_table('animal_breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('animal_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id', 'name', name='uq_animal_breed_type_name')
    )
    op.create_index(op.f('ix_animal_breeds_animal_type_id'), 'animal_breeds', ['animal_type_id'], unique=False)
    op.create_index(op.f('ix_animal_breeds_id'), 'animal_breeds', ['id'], unique=False)
    op.create_index(op.f('ix_animal_breeds_name'), 'animal_breeds', ['name'], unique=False)
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_service_category_business_name')
    )
    op.create_index(op.f('ix_service_categories_business_id'), 'service_categories', ['business_id'], unique=False)
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applies_to_all_animal_types', sa.Boolean(), nullable=False),
    sa.Column('applies_to_all_breeds', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_business_id'), 'services', ['business_id'], unique=False)
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_table('service_animal_breeds',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('animal_breed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_breed_id'], ['animal_breeds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'animal_breed_id')
    )
    op.create_table('service_animal_types',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('animal_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'animal_type_id')
    )
    op.create_table('service_staff',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['business_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'business_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_staff')
    op.drop_table('service_animal_types')
    op.drop_table('service_animal_breeds')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_index(op.f('ix_services_business_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_business_id'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index(op.f('ix_animal_breeds_name'), table_name='animal_breeds')
    op.drop_index(op.f('ix_animal_breeds_id'), table_name='animal_breeds')
    op.drop_index(op.f('ix_animal_breeds_animal_type_id'), table_name='animal_breeds')
    op.drop_table('animal_breeds')
    op.drop_index(op.f('ix_animal_types_name'), table_name='animal_types')
    op.drop_index(op.f('ix_animal_types_id'), table_name='animal_types')
    op.drop_table('animal_types')
    op.drop_index(op.f('ix_agreements_id'), table_name='agreements')
    op.drop_table('agreements')
    # ### end Alembic commands ###
