"""add_discount_columns_to_orders

Revision ID: 48c3366b35d9
Revises: 5368806b9233
Create Date: 2025-12-05 15:01:57.943427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c3366b35d9'
down_revision: Union[str, Sequence[str], None] = '5368806b9233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_type', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'discount_value')
    op.drop_column('orders', 'discount_type')
    # ### end Alembic commands ###
