"""add orders and payments tables

Revision ID: 5368806b9233
Revises: 28aeae4329cd
Create Date: 2025-12-05 13:43:35.690468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5368806b9233'
down_revision: Union[str, Sequence[str], None] = '28aeae4329cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('groomer_id', sa.Integer(), nullable=True),
    sa.Column('picked_up_by_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service_title', sa.String(length=500), nullable=False),
    sa.Column('groomer_name', sa.String(length=255), nullable=False),
    sa.Column('pet_name', sa.String(length=100), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['groomer_id'], ['business_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picked_up_by_id'], ['customer_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_business_created', 'orders', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_orders_business_order_status', 'orders', ['business_id', 'order_status'], unique=False)
    op.create_index('idx_orders_business_payment_status', 'orders', ['business_id', 'payment_status'], unique=False)
    op.create_index(op.f('ix_orders_appointment_id'), 'orders', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_orders_business_id'), 'orders', ['business_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_groomer_id'), 'orders', ['groomer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_pet_id'), 'orders', ['pet_id'], unique=False)
    op.create_index(op.f('ix_orders_picked_up_by_id'), 'orders', ['picked_up_by_id'], unique=False)
    op.create_index(op.f('ix_orders_service_id'), 'orders', ['service_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_device_id', sa.Integer(), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('square_checkout_id', sa.String(length=255), nullable=True),
    sa.Column('square_payment_id', sa.String(length=255), nullable=True),
    sa.Column('square_receipt_url', sa.String(length=512), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_device_id'], ['payment_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_by_id'], ['business_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_business_created', 'payments', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_payments_business_status', 'payments', ['business_id', 'status'], unique=False)
    op.create_index('idx_payments_order_status', 'payments', ['order_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_business_id'), 'payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_device_id'), 'payments', ['payment_device_id'], unique=False)
    op.create_index(op.f('ix_payments_processed_by_id'), 'payments', ['processed_by_id'], unique=False)
    op.create_index(op.f('ix_payments_square_checkout_id'), 'payments', ['square_checkout_id'], unique=True)
    op.create_index(op.f('ix_payments_square_payment_id'), 'payments', ['square_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_square_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_square_checkout_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_processed_by_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_device_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_business_id'), table_name='payments')
    op.drop_index('idx_payments_order_status', table_name='payments')
    op.drop_index('idx_payments_business_status', table_name='payments')
    op.drop_index('idx_payments_business_created', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_service_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_picked_up_by_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_pet_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_groomer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_appointment_id'), table_name='orders')
    op.drop_index('idx_orders_business_payment_status', table_name='orders')
    op.drop_index('idx_orders_business_order_status', table_name='orders')
    op.drop_index('idx_orders_business_created', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
