"""Add status column to agreements table

Revision ID: 99d8702328c3
Revises: a230ab728bba
Create Date: 2025-12-03 13:22:05.316367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d8702328c3'
down_revision: Union[str, Sequence[str], None] = 'a230ab728bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    agreement_status = sa.Enum('ACTIVE', 'DRAFT', 'ARCHIVED', name='agreementstatus')
    agreement_status.create(op.get_bind(), checkfirst=True)

    # Add the column with a default value
    op.add_column('agreements', sa.Column('status', agreement_status, nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'status')
    # Drop the enum type
    sa.Enum(name='agreementstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
