"""add_tip_amount_to_payments

Revision ID: 9d45f3c1889f
Revises: 48c3366b35d9
Create Date: 2025-12-05 15:22:17.986660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d45f3c1889f'
down_revision: Union[str, Sequence[str], None] = '48c3366b35d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'tip_amount')
    # ### end Alembic commands ###
