"""Add business_id to agreements table

Revision ID: a230ab728bba
Revises: 35d0c7ca3e3b
Create Date: 2025-12-03 13:07:54.447493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a230ab728bba'
down_revision: Union[str, Sequence[str], None] = '35d0c7ca3e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_agreements_business_id'), 'agreements', ['business_id'], unique=False)
    op.create_foreign_key(None, 'agreements', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_appointment_statuses_id'), 'appointment_statuses', ['id'], unique=False)
    op.drop_index(op.f('ix_business_user_roles_name'), table_name='business_user_roles')
    op.create_index(op.f('ix_business_user_roles_id'), 'business_user_roles', ['id'], unique=False)
    op.create_unique_constraint(None, 'business_user_roles', ['name'])
    op.alter_column('business_users', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'terminated', name='businessuserstatus'),
               type_=sa.Enum('active', 'inactive', 'terminated', name='businessuserstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::businessuserstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_users', 'status',
               existing_type=sa.Enum('active', 'inactive', 'terminated', name='businessuserstatus', native_enum=False),
               type_=postgresql.ENUM('active', 'inactive', 'terminated', name='businessuserstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::businessuserstatus"))
    op.drop_constraint(None, 'business_user_roles', type_='unique')
    op.drop_index(op.f('ix_business_user_roles_id'), table_name='business_user_roles')
    op.create_index(op.f('ix_business_user_roles_name'), 'business_user_roles', ['name'], unique=True)
    op.drop_index(op.f('ix_appointment_statuses_id'), table_name='appointment_statuses')
    op.drop_constraint(None, 'agreements', type_='foreignkey')
    op.drop_index(op.f('ix_agreements_business_id'), table_name='agreements')
    op.drop_column('agreements', 'business_id')
    # ### end Alembic commands ###
