"""add_compensation_and_availability

Revision ID: eabf84cc9eda
Revises: 34f5e77dfddb
Create Date: 2025-12-04 21:27:34.098807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabf84cc9eda'
down_revision: Union[str, Sequence[str], None] = '34f5e77dfddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['business_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_user_id', 'day_of_week', name='uq_staff_day')
    )
    op.create_index(op.f('ix_staff_availability_business_user_id'), 'staff_availability', ['business_user_id'], unique=False)
    op.create_index(op.f('ix_staff_availability_id'), 'staff_availability', ['id'], unique=False)
    op.add_column('business_users', sa.Column('compensation_type', sa.String(length=20), nullable=True))
    op.add_column('business_users', sa.Column('salary_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('business_users', sa.Column('salary_period', sa.String(length=10), nullable=True))
    op.add_column('business_users', sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('business_users', sa.Column('tip_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_users', 'tip_percent')
    op.drop_column('business_users', 'commission_percent')
    op.drop_column('business_users', 'salary_period')
    op.drop_column('business_users', 'salary_rate')
    op.drop_column('business_users', 'compensation_type')
    op.drop_index(op.f('ix_staff_availability_id'), table_name='staff_availability')
    op.drop_index(op.f('ix_staff_availability_business_user_id'), table_name='staff_availability')
    op.drop_table('staff_availability')
    # ### end Alembic commands ###
