"""add_default_groomer_to_pets

Revision ID: f069234b3611
Revises: 0996f4181221
Create Date: 2025-12-03 21:51:49.343291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f069234b3611'
down_revision: Union[str, Sequence[str], None] = '0996f4181221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('default_groomer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pets_default_groomer_id'), 'pets', ['default_groomer_id'], unique=False)
    op.create_foreign_key('fk_pets_default_groomer_id', 'pets', 'business_users', ['default_groomer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pets_default_groomer_id', 'pets', type_='foreignkey')
    op.drop_index(op.f('ix_pets_default_groomer_id'), table_name='pets')
    op.drop_column('pets', 'default_groomer_id')
    # ### end Alembic commands ###
