"""change notes to jsonb and add status and address fields to customer

Revision ID: f5ab9033eb2b
Revises: 99d8702328c3
Create Date: 2025-12-03 14:21:33.214506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ab9033eb2b'
down_revision: Union[str, Sequence[str], None] = '99d8702328c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_users', 'notes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('customers', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('customers', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.alter_column('customers', 'notes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'notes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'address_line2')
    op.drop_column('customers', 'address_line1')
    op.drop_column('customers', 'status')
    op.alter_column('customer_users', 'notes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
