"""add status and address fields to customer, change notes to jsonb

Revision ID: f7bcbf944415
Revises: f5ab9033eb2b
Create Date: 2025-12-03 14:42:55.954682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bcbf944415'
down_revision: Union[str, Sequence[str], None] = 'f5ab9033eb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
