"""add_order_and_display_text_to_appointment_status

Revision ID: f9d6e6e14a72
Revises: f069234b3611
Create Date: 2025-12-04 11:17:26.081339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d6e6e14a72'
down_revision: Union[str, Sequence[str], None] = 'f069234b3611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('appointment_statuses', sa.Column('display_text', sa.String(length=100), nullable=True))
    op.add_column('appointment_statuses', sa.Column('order', sa.Integer(), nullable=True))

    # Update existing records with display_text and order values
    # Status name -> (display_text, order)
    status_mapping = {
        'scheduled': ('Scheduled', 1),
        'confirmed': ('Checked In', 2),
        'in_progress': ('In Process', 3),
        'completed': ('Ready for Pickup', 4),
        'cancelled': ('Cancelled', 99),
        'no_show': ('No Show', 98),
    }

    for name, (display_text, order) in status_mapping.items():
        op.execute(
            f"UPDATE appointment_statuses SET display_text = '{display_text}', \"order\" = {order} WHERE name = '{name}'"
        )

    # Make columns NOT NULL after populating data
    op.alter_column('appointment_statuses', 'display_text', nullable=False)
    op.alter_column('appointment_statuses', 'order', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_statuses', 'order')
    op.drop_column('appointment_statuses', 'display_text')
    # ### end Alembic commands ###
